/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CHIBUZOR
 */
public class SetupItem extends javax.swing.JPanel {

    /**
     * Creates new form SetupItem
     */
    public SetupItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeesPositionLabel = new javax.swing.JLabel();
        StaffIdCheckBox = new javax.swing.JCheckBox();
        NameOfDepartmentLabel = new javax.swing.JLabel();
        EmployeesNameLabel = new javax.swing.JLabel();

        EmployeesPositionLabel.setText("Designation");

        StaffIdCheckBox.setText("StaffID");
        StaffIdCheckBox.setIconTextGap(10);

        NameOfDepartmentLabel.setText("Department");

        EmployeesNameLabel.setText("Name of Employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StaffIdCheckBox)
                .addGap(9, 9, 9)
                .addComponent(EmployeesNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameOfDepartmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeesPositionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(NameOfDepartmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(EmployeesNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(StaffIdCheckBox)
                .addComponent(EmployeesPositionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeesNameLabel;
    private javax.swing.JLabel EmployeesPositionLabel;
    private javax.swing.JLabel NameOfDepartmentLabel;
    private javax.swing.JCheckBox StaffIdCheckBox;
    // End of variables declaration//GEN-END:variables
}
